### ISSUE TITLE
업데이터 실행 시 자동 다운로드

### ISSUE THREAD

**Issue by chunghyang** [chunghyang/DalamudUpdaterKR#1]
당장 내가 보기에는
AssetsManager.cs 부분을 수정해야하는게 아닐까 싶은데

기본적으로 Dalamud.Updater를 실행하게되면 이 친구들이 먼저 자동으로
https://aonyx.ffxiv.wang/Dalamud/Asset/Meta
↑ 에 접속해서 자기들이 중국서버 전용으로 만들어놓은
1) Dalamud
→ 폴더 내 [ addons-Hooks-(버전) ]
2) Runtime (확실하지않음)
→ 폴더 내 [ runtime ]
3) DalamudAssets
→ 폴더 내 [ XIVlauncher ]
이 세 경로로 다운로드를 받고, 압축을 풀어주는?거 같은데,
이거 때문에 계속해서 한국 클라이언트에 작동되도록 만든 Dalamud랑 Assets를 덮어씌워줘야하는 문제가 생기는거 같음.

이전에 말해준 방법대로 해결을 해보긴할건데 이부분도 정말 내가 기초를 몰라서 공부를 해봐야할거 같아서....
업데이터 자체의 문제는 이 부분이 다인거 같음.

**Comment by HyunWoo-Nick** [comment]
#2  해당 내용 해결하는 PR
